# Generated by tools/generate.py -- do not edit by hand.
# Folds the typed character down to a glyph id and flags whether it is one we can draw.
scoreboard players set #valid letterbanners 0
execute if data storage letterbanners:io {args:{letter:" "}} run data modify storage letterbanners:io args.letter set value "space"
execute if data storage letterbanners:io {args:{letter:"!"}} run data modify storage letterbanners:io args.letter set value "exclamation"
execute if data storage letterbanners:io {args:{letter:"\""}} run data modify storage letterbanners:io args.letter set value "quote"
execute if data storage letterbanners:io {args:{letter:"%"}} run data modify storage letterbanners:io args.letter set value "percent"
execute if data storage letterbanners:io {args:{letter:"'"}} run data modify storage letterbanners:io args.letter set value "apostrophe"
execute if data storage letterbanners:io {args:{letter:"("}} run data modify storage letterbanners:io args.letter set value "paren_left"
execute if data storage letterbanners:io {args:{letter:")"}} run data modify storage letterbanners:io args.letter set value "paren_right"
execute if data storage letterbanners:io {args:{letter:"+"}} run data modify storage letterbanners:io args.letter set value "plus"
execute if data storage letterbanners:io {args:{letter:","}} run data modify storage letterbanners:io args.letter set value "comma"
execute if data storage letterbanners:io {args:{letter:"-"}} run data modify storage letterbanners:io args.letter set value "hyphen"
execute if data storage letterbanners:io {args:{letter:"."}} run data modify storage letterbanners:io args.letter set value "period"
execute if data storage letterbanners:io {args:{letter:"/"}} run data modify storage letterbanners:io args.letter set value "slash"
execute if data storage letterbanners:io {args:{letter:"0"}} run data modify storage letterbanners:io args.letter set value "0"
execute if data storage letterbanners:io {args:{letter:"1"}} run data modify storage letterbanners:io args.letter set value "1"
execute if data storage letterbanners:io {args:{letter:"2"}} run data modify storage letterbanners:io args.letter set value "2"
execute if data storage letterbanners:io {args:{letter:"3"}} run data modify storage letterbanners:io args.letter set value "3"
execute if data storage letterbanners:io {args:{letter:"4"}} run data modify storage letterbanners:io args.letter set value "4"
execute if data storage letterbanners:io {args:{letter:"5"}} run data modify storage letterbanners:io args.letter set value "5"
execute if data storage letterbanners:io {args:{letter:"6"}} run data modify storage letterbanners:io args.letter set value "6"
execute if data storage letterbanners:io {args:{letter:"7"}} run data modify storage letterbanners:io args.letter set value "7"
execute if data storage letterbanners:io {args:{letter:"8"}} run data modify storage letterbanners:io args.letter set value "8"
execute if data storage letterbanners:io {args:{letter:"9"}} run data modify storage letterbanners:io args.letter set value "9"
execute if data storage letterbanners:io {args:{letter:":"}} run data modify storage letterbanners:io args.letter set value "colon"
execute if data storage letterbanners:io {args:{letter:";"}} run data modify storage letterbanners:io args.letter set value "semicolon"
execute if data storage letterbanners:io {args:{letter:"="}} run data modify storage letterbanners:io args.letter set value "equals"
execute if data storage letterbanners:io {args:{letter:"A"}} run data modify storage letterbanners:io args.letter set value "a"
execute if data storage letterbanners:io {args:{letter:"B"}} run data modify storage letterbanners:io args.letter set value "b"
execute if data storage letterbanners:io {args:{letter:"C"}} run data modify storage letterbanners:io args.letter set value "c"
execute if data storage letterbanners:io {args:{letter:"D"}} run data modify storage letterbanners:io args.letter set value "d"
execute if data storage letterbanners:io {args:{letter:"E"}} run data modify storage letterbanners:io args.letter set value "e"
execute if data storage letterbanners:io {args:{letter:"F"}} run data modify storage letterbanners:io args.letter set value "f"
execute if data storage letterbanners:io {args:{letter:"G"}} run data modify storage letterbanners:io args.letter set value "g"
execute if data storage letterbanners:io {args:{letter:"H"}} run data modify storage letterbanners:io args.letter set value "h"
execute if data storage letterbanners:io {args:{letter:"I"}} run data modify storage letterbanners:io args.letter set value "i"
execute if data storage letterbanners:io {args:{letter:"J"}} run data modify storage letterbanners:io args.letter set value "j"
execute if data storage letterbanners:io {args:{letter:"K"}} run data modify storage letterbanners:io args.letter set value "k"
execute if data storage letterbanners:io {args:{letter:"L"}} run data modify storage letterbanners:io args.letter set value "l"
execute if data storage letterbanners:io {args:{letter:"M"}} run data modify storage letterbanners:io args.letter set value "m"
execute if data storage letterbanners:io {args:{letter:"N"}} run data modify storage letterbanners:io args.letter set value "n"
execute if data storage letterbanners:io {args:{letter:"O"}} run data modify storage letterbanners:io args.letter set value "o"
execute if data storage letterbanners:io {args:{letter:"P"}} run data modify storage letterbanners:io args.letter set value "p"
execute if data storage letterbanners:io {args:{letter:"Q"}} run data modify storage letterbanners:io args.letter set value "q"
execute if data storage letterbanners:io {args:{letter:"R"}} run data modify storage letterbanners:io args.letter set value "r"
execute if data storage letterbanners:io {args:{letter:"S"}} run data modify storage letterbanners:io args.letter set value "s"
execute if data storage letterbanners:io {args:{letter:"T"}} run data modify storage letterbanners:io args.letter set value "t"
execute if data storage letterbanners:io {args:{letter:"U"}} run data modify storage letterbanners:io args.letter set value "u"
execute if data storage letterbanners:io {args:{letter:"V"}} run data modify storage letterbanners:io args.letter set value "v"
execute if data storage letterbanners:io {args:{letter:"W"}} run data modify storage letterbanners:io args.letter set value "w"
execute if data storage letterbanners:io {args:{letter:"X"}} run data modify storage letterbanners:io args.letter set value "x"
execute if data storage letterbanners:io {args:{letter:"Y"}} run data modify storage letterbanners:io args.letter set value "y"
execute if data storage letterbanners:io {args:{letter:"Z"}} run data modify storage letterbanners:io args.letter set value "z"
execute if data storage letterbanners:io {args:{letter:"["}} run data modify storage letterbanners:io args.letter set value "bracket_left"
execute if data storage letterbanners:io {args:{letter:"\\"}} run data modify storage letterbanners:io args.letter set value "backslash"
execute if data storage letterbanners:io {args:{letter:"]"}} run data modify storage letterbanners:io args.letter set value "bracket_right"
execute if data storage letterbanners:io {args:{letter:"^"}} run data modify storage letterbanners:io args.letter set value "caret"
execute if data storage letterbanners:io {args:{letter:"_"}} run data modify storage letterbanners:io args.letter set value "underscore"
execute if data storage letterbanners:io {args:{letter:"a"}} run data modify storage letterbanners:io args.letter set value "a"
execute if data storage letterbanners:io {args:{letter:"b"}} run data modify storage letterbanners:io args.letter set value "b"
execute if data storage letterbanners:io {args:{letter:"c"}} run data modify storage letterbanners:io args.letter set value "c"
execute if data storage letterbanners:io {args:{letter:"d"}} run data modify storage letterbanners:io args.letter set value "d"
execute if data storage letterbanners:io {args:{letter:"e"}} run data modify storage letterbanners:io args.letter set value "e"
execute if data storage letterbanners:io {args:{letter:"f"}} run data modify storage letterbanners:io args.letter set value "f"
execute if data storage letterbanners:io {args:{letter:"g"}} run data modify storage letterbanners:io args.letter set value "g"
execute if data storage letterbanners:io {args:{letter:"h"}} run data modify storage letterbanners:io args.letter set value "h"
execute if data storage letterbanners:io {args:{letter:"i"}} run data modify storage letterbanners:io args.letter set value "i"
execute if data storage letterbanners:io {args:{letter:"j"}} run data modify storage letterbanners:io args.letter set value "j"
execute if data storage letterbanners:io {args:{letter:"k"}} run data modify storage letterbanners:io args.letter set value "k"
execute if data storage letterbanners:io {args:{letter:"l"}} run data modify storage letterbanners:io args.letter set value "l"
execute if data storage letterbanners:io {args:{letter:"m"}} run data modify storage letterbanners:io args.letter set value "m"
execute if data storage letterbanners:io {args:{letter:"n"}} run data modify storage letterbanners:io args.letter set value "n"
execute if data storage letterbanners:io {args:{letter:"o"}} run data modify storage letterbanners:io args.letter set value "o"
execute if data storage letterbanners:io {args:{letter:"p"}} run data modify storage letterbanners:io args.letter set value "p"
execute if data storage letterbanners:io {args:{letter:"q"}} run data modify storage letterbanners:io args.letter set value "q"
execute if data storage letterbanners:io {args:{letter:"r"}} run data modify storage letterbanners:io args.letter set value "r"
execute if data storage letterbanners:io {args:{letter:"s"}} run data modify storage letterbanners:io args.letter set value "s"
execute if data storage letterbanners:io {args:{letter:"t"}} run data modify storage letterbanners:io args.letter set value "t"
execute if data storage letterbanners:io {args:{letter:"u"}} run data modify storage letterbanners:io args.letter set value "u"
execute if data storage letterbanners:io {args:{letter:"v"}} run data modify storage letterbanners:io args.letter set value "v"
execute if data storage letterbanners:io {args:{letter:"w"}} run data modify storage letterbanners:io args.letter set value "w"
execute if data storage letterbanners:io {args:{letter:"x"}} run data modify storage letterbanners:io args.letter set value "x"
execute if data storage letterbanners:io {args:{letter:"y"}} run data modify storage letterbanners:io args.letter set value "y"
execute if data storage letterbanners:io {args:{letter:"z"}} run data modify storage letterbanners:io args.letter set value "z"
execute if data storage letterbanners:io {args:{letter:"|"}} run data modify storage letterbanners:io args.letter set value "pipe"
execute if data storage letterbanners:io {args:{letter:"0"}} run scoreboard players set #valid letterbanners 1
execute if data storage letterbanners:io {args:{letter:"1"}} run scoreboard players set #valid letterbanners 1
execute if data storage letterbanners:io {args:{letter:"2"}} run scoreboard players set #valid letterbanners 1
execute if data storage letterbanners:io {args:{letter:"3"}} run scoreboard players set #valid letterbanners 1
execute if data storage letterbanners:io {args:{letter:"4"}} run scoreboard players set #valid letterbanners 1
execute if data storage letterbanners:io {args:{letter:"5"}} run scoreboard players set #valid letterbanners 1
execute if data storage letterbanners:io {args:{letter:"6"}} run scoreboard players set #valid letterbanners 1
execute if data storage letterbanners:io {args:{letter:"7"}} run scoreboard players set #valid letterbanners 1
execute if data storage letterbanners:io {args:{letter:"8"}} run scoreboard players set #valid letterbanners 1
execute if data storage letterbanners:io {args:{letter:"9"}} run scoreboard players set #valid letterbanners 1
execute if data storage letterbanners:io {args:{letter:"a"}} run scoreboard players set #valid letterbanners 1
execute if data storage letterbanners:io {args:{letter:"apostrophe"}} run scoreboard players set #valid letterbanners 1
execute if data storage letterbanners:io {args:{letter:"b"}} run scoreboard players set #valid letterbanners 1
execute if data storage letterbanners:io {args:{letter:"backslash"}} run scoreboard players set #valid letterbanners 1
execute if data storage letterbanners:io {args:{letter:"bracket_left"}} run scoreboard players set #valid letterbanners 1
execute if data storage letterbanners:io {args:{letter:"bracket_right"}} run scoreboard players set #valid letterbanners 1
execute if data storage letterbanners:io {args:{letter:"c"}} run scoreboard players set #valid letterbanners 1
execute if data storage letterbanners:io {args:{letter:"caret"}} run scoreboard players set #valid letterbanners 1
execute if data storage letterbanners:io {args:{letter:"colon"}} run scoreboard players set #valid letterbanners 1
execute if data storage letterbanners:io {args:{letter:"comma"}} run scoreboard players set #valid letterbanners 1
execute if data storage letterbanners:io {args:{letter:"d"}} run scoreboard players set #valid letterbanners 1
execute if data storage letterbanners:io {args:{letter:"e"}} run scoreboard players set #valid letterbanners 1
execute if data storage letterbanners:io {args:{letter:"equals"}} run scoreboard players set #valid letterbanners 1
execute if data storage letterbanners:io {args:{letter:"exclamation"}} run scoreboard players set #valid letterbanners 1
execute if data storage letterbanners:io {args:{letter:"f"}} run scoreboard players set #valid letterbanners 1
execute if data storage letterbanners:io {args:{letter:"g"}} run scoreboard players set #valid letterbanners 1
execute if data storage letterbanners:io {args:{letter:"h"}} run scoreboard players set #valid letterbanners 1
execute if data storage letterbanners:io {args:{letter:"hyphen"}} run scoreboard players set #valid letterbanners 1
execute if data storage letterbanners:io {args:{letter:"i"}} run scoreboard players set #valid letterbanners 1
execute if data storage letterbanners:io {args:{letter:"j"}} run scoreboard players set #valid letterbanners 1
execute if data storage letterbanners:io {args:{letter:"k"}} run scoreboard players set #valid letterbanners 1
execute if data storage letterbanners:io {args:{letter:"l"}} run scoreboard players set #valid letterbanners 1
execute if data storage letterbanners:io {args:{letter:"m"}} run scoreboard players set #valid letterbanners 1
execute if data storage letterbanners:io {args:{letter:"n"}} run scoreboard players set #valid letterbanners 1
execute if data storage letterbanners:io {args:{letter:"o"}} run scoreboard players set #valid letterbanners 1
execute if data storage letterbanners:io {args:{letter:"p"}} run scoreboard players set #valid letterbanners 1
execute if data storage letterbanners:io {args:{letter:"paren_left"}} run scoreboard players set #valid letterbanners 1
execute if data storage letterbanners:io {args:{letter:"paren_right"}} run scoreboard players set #valid letterbanners 1
execute if data storage letterbanners:io {args:{letter:"percent"}} run scoreboard players set #valid letterbanners 1
execute if data storage letterbanners:io {args:{letter:"period"}} run scoreboard players set #valid letterbanners 1
execute if data storage letterbanners:io {args:{letter:"pipe"}} run scoreboard players set #valid letterbanners 1
execute if data storage letterbanners:io {args:{letter:"plus"}} run scoreboard players set #valid letterbanners 1
execute if data storage letterbanners:io {args:{letter:"q"}} run scoreboard players set #valid letterbanners 1
execute if data storage letterbanners:io {args:{letter:"quote"}} run scoreboard players set #valid letterbanners 1
execute if data storage letterbanners:io {args:{letter:"r"}} run scoreboard players set #valid letterbanners 1
execute if data storage letterbanners:io {args:{letter:"s"}} run scoreboard players set #valid letterbanners 1
execute if data storage letterbanners:io {args:{letter:"semicolon"}} run scoreboard players set #valid letterbanners 1
execute if data storage letterbanners:io {args:{letter:"slash"}} run scoreboard players set #valid letterbanners 1
execute if data storage letterbanners:io {args:{letter:"space"}} run scoreboard players set #valid letterbanners 1
execute if data storage letterbanners:io {args:{letter:"t"}} run scoreboard players set #valid letterbanners 1
execute if data storage letterbanners:io {args:{letter:"u"}} run scoreboard players set #valid letterbanners 1
execute if data storage letterbanners:io {args:{letter:"underscore"}} run scoreboard players set #valid letterbanners 1
execute if data storage letterbanners:io {args:{letter:"v"}} run scoreboard players set #valid letterbanners 1
execute if data storage letterbanners:io {args:{letter:"w"}} run scoreboard players set #valid letterbanners 1
execute if data storage letterbanners:io {args:{letter:"x"}} run scoreboard players set #valid letterbanners 1
execute if data storage letterbanners:io {args:{letter:"y"}} run scoreboard players set #valid letterbanners 1
execute if data storage letterbanners:io {args:{letter:"z"}} run scoreboard players set #valid letterbanners 1
