# Generated by tools/generate.py -- do not edit by hand.
# 1
$give @s minecraft:$(bg)_banner[minecraft:banner_patterns=[{pattern:"minecraft:stripe_bottom",color:"$(fg)"},{pattern:"minecraft:stripe_center",color:"$(fg)"},{pattern:"minecraft:square_top_left",color:"$(fg)"}$(extra)],minecraft:item_name={"text": "1", "italic": false}]
