# Generated by tools/generate.py -- do not edit by hand.
# 2
$give @s minecraft:$(bg)_banner[minecraft:banner_patterns=[{pattern:"minecraft:half_horizontal",color:"$(fg)"},{pattern:"minecraft:rhombus",color:"$(bg)"},{pattern:"minecraft:stripe_middle",color:"$(bg)"},{pattern:"minecraft:stripe_downleft",color:"$(fg)"},{pattern:"minecraft:stripe_bottom",color:"$(fg)"}$(extra)],minecraft:item_name={"text": "2", "italic": false}]
