# Generated by tools/generate.py -- do not edit by hand.
# 3
$give @s minecraft:$(bg)_banner[minecraft:banner_patterns=[{pattern:"minecraft:stripe_right",color:"$(fg)"},{pattern:"minecraft:stripe_top",color:"$(fg)"},{pattern:"minecraft:stripe_middle",color:"$(fg)"},{pattern:"minecraft:stripe_bottom",color:"$(fg)"}$(extra)],minecraft:item_name={"text": "3", "italic": false}]
