# Generated by tools/generate.py -- do not edit by hand.
# 4
$give @s minecraft:$(bg)_banner[minecraft:banner_patterns=[{pattern:"minecraft:base",color:"$(fg)"},{pattern:"minecraft:half_horizontal",color:"$(bg)"},{pattern:"minecraft:stripe_bottom",color:"$(bg)"},{pattern:"minecraft:stripe_right",color:"$(fg)"},{pattern:"minecraft:stripe_left",color:"$(fg)"},{pattern:"minecraft:square_bottom_left",color:"$(bg)"}$(extra)],minecraft:item_name={"text": "4", "italic": false}]
