# Generated by tools/generate.py -- do not edit by hand.
# 5
$give @s minecraft:$(bg)_banner[minecraft:banner_patterns=[{pattern:"minecraft:base",color:"$(fg)"},{pattern:"minecraft:half_horizontal",color:"$(bg)"},{pattern:"minecraft:rhombus",color:"$(bg)"},{pattern:"minecraft:stripe_middle",color:"$(bg)"},{pattern:"minecraft:stripe_downright",color:"$(fg)"},{pattern:"minecraft:stripe_top",color:"$(fg)"}$(extra)],minecraft:item_name={"text": "5", "italic": false}]
