# Generated by tools/generate.py -- do not edit by hand.
# 6
$give @s minecraft:$(bg)_banner[minecraft:banner_patterns=[{pattern:"minecraft:base",color:"$(fg)"},{pattern:"minecraft:half_horizontal",color:"$(bg)"},{pattern:"minecraft:stripe_center",color:"$(bg)"},{pattern:"minecraft:stripe_bottom",color:"$(fg)"},{pattern:"minecraft:stripe_middle",color:"$(fg)"},{pattern:"minecraft:stripe_left",color:"$(fg)"},{pattern:"minecraft:stripe_top",color:"$(fg)"}$(extra)],minecraft:item_name={"text": "6", "italic": false}]
