# Generated by tools/generate.py -- do not edit by hand.
# 9
$give @s minecraft:$(bg)_banner[minecraft:banner_patterns=[{pattern:"minecraft:half_horizontal",color:"$(fg)"},{pattern:"minecraft:stripe_center",color:"$(bg)"},{pattern:"minecraft:stripe_top",color:"$(fg)"},{pattern:"minecraft:stripe_middle",color:"$(fg)"},{pattern:"minecraft:stripe_right",color:"$(fg)"}$(extra)],minecraft:item_name={"text": "9", "italic": false}]
