# Generated by tools/generate.py -- do not edit by hand.
# B
$give @s minecraft:$(bg)_banner[minecraft:banner_patterns=[{pattern:"minecraft:base",color:"$(fg)"},{pattern:"minecraft:rhombus",color:"$(bg)"},{pattern:"minecraft:half_vertical",color:"$(bg)"},{pattern:"minecraft:stripe_top",color:"$(fg)"},{pattern:"minecraft:stripe_bottom",color:"$(fg)"},{pattern:"minecraft:stripe_left",color:"$(fg)"},{pattern:"minecraft:stripe_middle",color:"$(fg)"}$(extra)],minecraft:item_name={"text": "B", "italic": false}]
