# Generated by tools/generate.py -- do not edit by hand.
# \
$give @s minecraft:$(bg)_banner[minecraft:banner_patterns=[{pattern:"minecraft:stripe_downright",color:"$(fg)"}$(extra)],minecraft:item_name={"text": "\\", "italic": false}]
