# Generated by tools/generate.py -- do not edit by hand.
# ]
$give @s minecraft:$(bg)_banner[minecraft:banner_patterns=[{pattern:"minecraft:stripe_right",color:"$(fg)"},{pattern:"minecraft:stripe_top",color:"$(fg)"},{pattern:"minecraft:stripe_bottom",color:"$(fg)"},{pattern:"minecraft:stripe_left",color:"$(bg)"}$(extra)],minecraft:item_name={"text": "]", "italic": false}]
