# Generated by tools/generate.py -- do not edit by hand.
# C
$give @s minecraft:$(bg)_banner[minecraft:banner_patterns=[{pattern:"minecraft:stripe_left",color:"$(fg)"},{pattern:"minecraft:stripe_bottom",color:"$(fg)"},{pattern:"minecraft:stripe_top",color:"$(fg)"}$(extra)],minecraft:item_name={"text": "C", "italic": false}]
