# Generated by tools/generate.py -- do not edit by hand.
# ^
$give @s minecraft:$(bg)_banner[minecraft:banner_patterns=[{pattern:"minecraft:half_horizontal",color:"$(fg)"},{pattern:"minecraft:stripe_center",color:"$(bg)"},{pattern:"minecraft:stripe_top",color:"$(fg)"}$(extra)],minecraft:item_name={"text": "^", "italic": false}]
