# Generated by tools/generate.py -- do not edit by hand.
# F
$give @s minecraft:$(bg)_banner[minecraft:banner_patterns=[{pattern:"minecraft:stripe_top",color:"$(fg)"},{pattern:"minecraft:stripe_middle",color:"$(fg)"},{pattern:"minecraft:stripe_left",color:"$(fg)"}$(extra)],minecraft:item_name={"text": "F", "italic": false}]
