# Generated by tools/generate.py -- do not edit by hand.
# H
$give @s minecraft:$(bg)_banner[minecraft:banner_patterns=[{pattern:"minecraft:stripe_right",color:"$(fg)"},{pattern:"minecraft:stripe_left",color:"$(fg)"},{pattern:"minecraft:stripe_middle",color:"$(fg)"}$(extra)],minecraft:item_name={"text": "H", "italic": false}]
