# Generated by tools/generate.py -- do not edit by hand.
# K
$give @s minecraft:$(bg)_banner[minecraft:banner_patterns=[{pattern:"minecraft:stripe_downright",color:"$(fg)"},{pattern:"minecraft:stripe_downleft",color:"$(fg)"},{pattern:"minecraft:half_vertical",color:"$(fg)"}$(extra)],minecraft:item_name={"text": "K", "italic": false}]
