# Generated by tools/generate.py -- do not edit by hand.
# (
$give @s minecraft:$(bg)_banner[minecraft:banner_patterns=[{pattern:"minecraft:base",color:"$(fg)"},{pattern:"minecraft:stripe_right",color:"$(bg)"},{pattern:"minecraft:stripe_bottom",color:"$(bg)"},{pattern:"minecraft:stripe_left",color:"$(bg)"},{pattern:"minecraft:stripe_top",color:"$(bg)"},{pattern:"minecraft:square_top_right",color:"$(fg)"},{pattern:"minecraft:square_bottom_right",color:"$(fg)"}$(extra)],minecraft:item_name={"text": "(", "italic": false}]
