# Generated by tools/generate.py -- do not edit by hand.
# .
$give @s minecraft:$(bg)_banner[minecraft:banner_patterns=[{pattern:"minecraft:square_bottom_right",color:"$(fg)"}$(extra)],minecraft:item_name={"text": ".", "italic": false}]
