# Generated by tools/generate.py -- do not edit by hand.
# S
$give @s minecraft:$(bg)_banner[minecraft:banner_patterns=[{pattern:"minecraft:base",color:"$(fg)"},{pattern:"minecraft:rhombus",color:"$(bg)"},{pattern:"minecraft:stripe_middle",color:"$(bg)"},{pattern:"minecraft:stripe_downright",color:"$(fg)"}$(extra)],minecraft:item_name={"text": "S", "italic": false}]
