# Generated by tools/generate.py -- do not edit by hand.
# Blank
$give @s minecraft:$(bg)_banner[minecraft:banner_patterns=[{pattern:"minecraft:base",color:"$(bg)"}$(extra)],minecraft:item_name={"text": "Blank", "italic": false}]
