# Generated by tools/generate.py -- do not edit by hand.
# T
$give @s minecraft:$(bg)_banner[minecraft:banner_patterns=[{pattern:"minecraft:stripe_center",color:"$(fg)"},{pattern:"minecraft:stripe_top",color:"$(fg)"}$(extra)],minecraft:item_name={"text": "T", "italic": false}]
