# Generated by tools/generate.py -- do not edit by hand.
# _
$give @s minecraft:$(bg)_banner[minecraft:banner_patterns=[{pattern:"minecraft:stripe_bottom",color:"$(fg)"}$(extra)],minecraft:item_name={"text": "_", "italic": false}]
