# Generated by tools/generate.py -- do not edit by hand.
# V
$give @s minecraft:$(bg)_banner[minecraft:banner_patterns=[{pattern:"minecraft:base",color:"$(fg)"},{pattern:"minecraft:half_horizontal",color:"$(bg)"},{pattern:"minecraft:rhombus",color:"$(bg)"},{pattern:"minecraft:stripe_right",color:"$(fg)"},{pattern:"minecraft:stripe_left",color:"$(fg)"}$(extra)],minecraft:item_name={"text": "V", "italic": false}]
