# Generated by tools/generate.py -- do not edit by hand.
# W
$give @s minecraft:$(bg)_banner[minecraft:banner_patterns=[{pattern:"minecraft:triangle_bottom",color:"$(fg)"},{pattern:"minecraft:triangles_bottom",color:"$(bg)"},{pattern:"minecraft:stripe_right",color:"$(fg)"},{pattern:"minecraft:stripe_left",color:"$(fg)"}$(extra)],minecraft:item_name={"text": "W", "italic": false}]
