# Generated by tools/generate.py -- do not edit by hand.
# Z
$give @s minecraft:$(bg)_banner[minecraft:banner_patterns=[{pattern:"minecraft:stripe_top",color:"$(fg)"},{pattern:"minecraft:stripe_bottom",color:"$(fg)"},{pattern:"minecraft:stripe_downleft",color:"$(fg)"}$(extra)],minecraft:item_name={"text": "Z", "italic": false}]
