# Generated by tools/generate.py -- do not edit by hand.
# 5
$give @s minecraft:$(bg)_banner[minecraft:banner_patterns=[{pattern:"minecraft:stripe_bottom",color:"$(fg)"},{pattern:"minecraft:rhombus",color:"$(bg)"},{pattern:"minecraft:stripe_top",color:"$(fg)"},{pattern:"minecraft:stripe_downright",color:"$(fg)"},{pattern:"minecraft:border",color:"$(bg)"}$(extra)],minecraft:item_name={"text": "5", "italic": false}]
