# Generated by tools/generate.py -- do not edit by hand.
# 7
$give @s minecraft:$(bg)_banner[minecraft:banner_patterns=[{pattern:"minecraft:stripe_downleft",color:"$(fg)"},{pattern:"minecraft:stripe_top",color:"$(fg)"},{pattern:"minecraft:border",color:"$(bg)"}$(extra)],minecraft:item_name={"text": "7", "italic": false}]
