# Generated by tools/generate.py -- do not edit by hand.
# A
$give @s minecraft:$(bg)_banner[minecraft:banner_patterns=[{pattern:"minecraft:stripe_right",color:"$(fg)"},{pattern:"minecraft:stripe_left",color:"$(fg)"},{pattern:"minecraft:stripe_middle",color:"$(fg)"},{pattern:"minecraft:stripe_top",color:"$(fg)"},{pattern:"minecraft:border",color:"$(bg)"}$(extra)],minecraft:item_name={"text": "A", "italic": false}]
