# Generated by tools/generate.py -- do not edit by hand.
# :
$give @s minecraft:$(bg)_banner[minecraft:banner_patterns=[{pattern:"minecraft:square_top_right",color:"$(fg)"},{pattern:"minecraft:square_bottom_right",color:"$(fg)"},{pattern:"minecraft:border",color:"$(bg)"}$(extra)],minecraft:item_name={"text": ":", "italic": false}]
