# Generated by tools/generate.py -- do not edit by hand.
# =
$give @s minecraft:$(bg)_banner[minecraft:banner_patterns=[{pattern:"minecraft:base",color:"$(fg)"},{pattern:"minecraft:stripe_top",color:"$(bg)"},{pattern:"minecraft:stripe_bottom",color:"$(bg)"},{pattern:"minecraft:stripe_middle",color:"$(bg)"},{pattern:"minecraft:border",color:"$(bg)"}$(extra)],minecraft:item_name={"text": "=", "italic": false}]
