# Generated by tools/generate.py -- do not edit by hand.
# J
$give @s minecraft:$(bg)_banner[minecraft:banner_patterns=[{pattern:"minecraft:stripe_left",color:"$(fg)"},{pattern:"minecraft:half_horizontal",color:"$(bg)"},{pattern:"minecraft:stripe_bottom",color:"$(fg)"},{pattern:"minecraft:stripe_right",color:"$(fg)"},{pattern:"minecraft:border",color:"$(bg)"}$(extra)],minecraft:item_name={"text": "J", "italic": false}]
