# Generated by tools/generate.py -- do not edit by hand.
# N
$give @s minecraft:$(bg)_banner[minecraft:banner_patterns=[{pattern:"minecraft:stripe_left",color:"$(fg)"},{pattern:"minecraft:triangle_top",color:"$(bg)"},{pattern:"minecraft:stripe_downright",color:"$(fg)"},{pattern:"minecraft:stripe_right",color:"$(fg)"},{pattern:"minecraft:border",color:"$(bg)"}$(extra)],minecraft:item_name={"text": "N", "italic": false}]
