# Generated by tools/generate.py -- do not edit by hand.
# V
$give @s minecraft:$(bg)_banner[minecraft:banner_patterns=[{pattern:"minecraft:stripe_downleft",color:"$(fg)"},{pattern:"minecraft:stripe_left",color:"$(fg)"},{pattern:"minecraft:triangle_bottom",color:"$(bg)"},{pattern:"minecraft:stripe_downleft",color:"$(fg)"},{pattern:"minecraft:border",color:"$(bg)"}$(extra)],minecraft:item_name={"text": "V", "italic": false}]
