# Generated by tools/generate.py -- do not edit by hand.
# X
$give @s minecraft:$(bg)_banner[minecraft:banner_patterns=[{pattern:"minecraft:cross",color:"$(fg)"},{pattern:"minecraft:border",color:"$(bg)"}$(extra)],minecraft:item_name={"text": "X", "italic": false}]
