# Generated by tools/generate.py -- do not edit by hand.
# Y
$give @s minecraft:$(bg)_banner[minecraft:banner_patterns=[{pattern:"minecraft:stripe_downright",color:"$(fg)"},{pattern:"minecraft:half_horizontal_bottom",color:"$(bg)"},{pattern:"minecraft:stripe_downleft",color:"$(fg)"},{pattern:"minecraft:border",color:"$(bg)"}$(extra)],minecraft:item_name={"text": "Y", "italic": false}]
