# Generated by tools/generate.py -- do not edit by hand.
# All Digits (0-9)
$function letterbanners:create {letter:"0",fg:"$(fg)",bg:"$(bg)",fade:"$(fade)",size:"$(size)"}
$function letterbanners:create {letter:"1",fg:"$(fg)",bg:"$(bg)",fade:"$(fade)",size:"$(size)"}
$function letterbanners:create {letter:"2",fg:"$(fg)",bg:"$(bg)",fade:"$(fade)",size:"$(size)"}
$function letterbanners:create {letter:"3",fg:"$(fg)",bg:"$(bg)",fade:"$(fade)",size:"$(size)"}
$function letterbanners:create {letter:"4",fg:"$(fg)",bg:"$(bg)",fade:"$(fade)",size:"$(size)"}
$function letterbanners:create {letter:"5",fg:"$(fg)",bg:"$(bg)",fade:"$(fade)",size:"$(size)"}
$function letterbanners:create {letter:"6",fg:"$(fg)",bg:"$(bg)",fade:"$(fade)",size:"$(size)"}
$function letterbanners:create {letter:"7",fg:"$(fg)",bg:"$(bg)",fade:"$(fade)",size:"$(size)"}
$function letterbanners:create {letter:"8",fg:"$(fg)",bg:"$(bg)",fade:"$(fade)",size:"$(size)"}
$function letterbanners:create {letter:"9",fg:"$(fg)",bg:"$(bg)",fade:"$(fade)",size:"$(size)"}
playsound minecraft:ui.loom.take_result master @s
