# Generated by tools/generate.py -- do not edit by hand.
# All Letters (A-Z)
$function letterbanners:create {letter:"a",fg:"$(fg)",bg:"$(bg)",fade:"$(fade)",size:"$(size)"}
$function letterbanners:create {letter:"b",fg:"$(fg)",bg:"$(bg)",fade:"$(fade)",size:"$(size)"}
$function letterbanners:create {letter:"c",fg:"$(fg)",bg:"$(bg)",fade:"$(fade)",size:"$(size)"}
$function letterbanners:create {letter:"d",fg:"$(fg)",bg:"$(bg)",fade:"$(fade)",size:"$(size)"}
$function letterbanners:create {letter:"e",fg:"$(fg)",bg:"$(bg)",fade:"$(fade)",size:"$(size)"}
$function letterbanners:create {letter:"f",fg:"$(fg)",bg:"$(bg)",fade:"$(fade)",size:"$(size)"}
$function letterbanners:create {letter:"g",fg:"$(fg)",bg:"$(bg)",fade:"$(fade)",size:"$(size)"}
$function letterbanners:create {letter:"h",fg:"$(fg)",bg:"$(bg)",fade:"$(fade)",size:"$(size)"}
$function letterbanners:create {letter:"i",fg:"$(fg)",bg:"$(bg)",fade:"$(fade)",size:"$(size)"}
$function letterbanners:create {letter:"j",fg:"$(fg)",bg:"$(bg)",fade:"$(fade)",size:"$(size)"}
$function letterbanners:create {letter:"k",fg:"$(fg)",bg:"$(bg)",fade:"$(fade)",size:"$(size)"}
$function letterbanners:create {letter:"l",fg:"$(fg)",bg:"$(bg)",fade:"$(fade)",size:"$(size)"}
$function letterbanners:create {letter:"m",fg:"$(fg)",bg:"$(bg)",fade:"$(fade)",size:"$(size)"}
$function letterbanners:create {letter:"n",fg:"$(fg)",bg:"$(bg)",fade:"$(fade)",size:"$(size)"}
$function letterbanners:create {letter:"o",fg:"$(fg)",bg:"$(bg)",fade:"$(fade)",size:"$(size)"}
$function letterbanners:create {letter:"p",fg:"$(fg)",bg:"$(bg)",fade:"$(fade)",size:"$(size)"}
$function letterbanners:create {letter:"q",fg:"$(fg)",bg:"$(bg)",fade:"$(fade)",size:"$(size)"}
$function letterbanners:create {letter:"r",fg:"$(fg)",bg:"$(bg)",fade:"$(fade)",size:"$(size)"}
$function letterbanners:create {letter:"s",fg:"$(fg)",bg:"$(bg)",fade:"$(fade)",size:"$(size)"}
$function letterbanners:create {letter:"t",fg:"$(fg)",bg:"$(bg)",fade:"$(fade)",size:"$(size)"}
$function letterbanners:create {letter:"u",fg:"$(fg)",bg:"$(bg)",fade:"$(fade)",size:"$(size)"}
$function letterbanners:create {letter:"v",fg:"$(fg)",bg:"$(bg)",fade:"$(fade)",size:"$(size)"}
$function letterbanners:create {letter:"w",fg:"$(fg)",bg:"$(bg)",fade:"$(fade)",size:"$(size)"}
$function letterbanners:create {letter:"x",fg:"$(fg)",bg:"$(bg)",fade:"$(fade)",size:"$(size)"}
$function letterbanners:create {letter:"y",fg:"$(fg)",bg:"$(bg)",fade:"$(fade)",size:"$(size)"}
$function letterbanners:create {letter:"z",fg:"$(fg)",bg:"$(bg)",fade:"$(fade)",size:"$(size)"}
playsound minecraft:ui.loom.take_result master @s
