# Generated by tools/generate.py -- do not edit by hand.
# All Symbols
$function letterbanners:create {letter:"exclamation",fg:"$(fg)",bg:"$(bg)",fade:"$(fade)",size:"$(size)"}
$function letterbanners:create {letter:"percent",fg:"$(fg)",bg:"$(bg)",fade:"$(fade)",size:"$(size)"}
$function letterbanners:create {letter:"caret",fg:"$(fg)",bg:"$(bg)",fade:"$(fade)",size:"$(size)"}
$function letterbanners:create {letter:"underscore",fg:"$(fg)",bg:"$(bg)",fade:"$(fade)",size:"$(size)"}
$function letterbanners:create {letter:"hyphen",fg:"$(fg)",bg:"$(bg)",fade:"$(fade)",size:"$(size)"}
$function letterbanners:create {letter:"bracket_left",fg:"$(fg)",bg:"$(bg)",fade:"$(fade)",size:"$(size)"}
$function letterbanners:create {letter:"bracket_right",fg:"$(fg)",bg:"$(bg)",fade:"$(fade)",size:"$(size)"}
$function letterbanners:create {letter:"pipe",fg:"$(fg)",bg:"$(bg)",fade:"$(fade)",size:"$(size)"}
$function letterbanners:create {letter:"colon",fg:"$(fg)",bg:"$(bg)",fade:"$(fade)",size:"$(size)"}
$function letterbanners:create {letter:"semicolon",fg:"$(fg)",bg:"$(bg)",fade:"$(fade)",size:"$(size)"}
$function letterbanners:create {letter:"equals",fg:"$(fg)",bg:"$(bg)",fade:"$(fade)",size:"$(size)"}
$function letterbanners:create {letter:"quote",fg:"$(fg)",bg:"$(bg)",fade:"$(fade)",size:"$(size)"}
$function letterbanners:create {letter:"apostrophe",fg:"$(fg)",bg:"$(bg)",fade:"$(fade)",size:"$(size)"}
$function letterbanners:create {letter:"comma",fg:"$(fg)",bg:"$(bg)",fade:"$(fade)",size:"$(size)"}
$function letterbanners:create {letter:"period",fg:"$(fg)",bg:"$(bg)",fade:"$(fade)",size:"$(size)"}
$function letterbanners:create {letter:"plus",fg:"$(fg)",bg:"$(bg)",fade:"$(fade)",size:"$(size)"}
$function letterbanners:create {letter:"paren_left",fg:"$(fg)",bg:"$(bg)",fade:"$(fade)",size:"$(size)"}
$function letterbanners:create {letter:"paren_right",fg:"$(fg)",bg:"$(bg)",fade:"$(fade)",size:"$(size)"}
$function letterbanners:create {letter:"slash",fg:"$(fg)",bg:"$(bg)",fade:"$(fade)",size:"$(size)"}
$function letterbanners:create {letter:"backslash",fg:"$(fg)",bg:"$(bg)",fade:"$(fade)",size:"$(size)"}
playsound minecraft:ui.loom.take_result master @s
